require 'fileutils'
require '../visual_studio_dot_net'

task :default => :test

task :test => :build do
  in_fixture_copy { sh "../test/Debug/UpdateInstallerTest.exe" }
  in_fixture_copy { ruby "../update_installer_test.rb" }
end

task :build do
  VisualStudioDotNet.build "UpdateInstaller.vcproj", "Release"
  FileUtils.cd "test" do
    VisualStudioDotNet.build "UpdateInstallerTest.vcproj", "Debug"
  end
end

task :clean do
  VisualStudioDotNet.clean "UpdateInstaller.vcproj", "Release"
end

def in_fixture_copy
  FileUtils.rm_rf "fixture-temp"
  FileUtils.cp_r "fixture", "fixture-temp"
  FileUtils.cd "fixture-temp" do 
    yield
  end
  FileUtils.rm_rf "fixture-temp"
end
