#!/bin/bash -e

find Common wx runtime tools \
    \! -name resource.h \! -name resources.cpp \
    \( -name \*.cpp -o -name \*.h -o -name \*.ss -o -name \*.rb -o \
       -name \*.rake -o -name Rakefile \)
